project:
  type: website
  output-dir: docs
  resources:
    - "api/**"

website:
  title: "ì„¸ìƒ ëª¨ë“  í†µê³„ ì´ì•¼ê¸°"
  search: true
  page-navigation: true
  navbar:
    # sticky: true   # ìŠ¤í¬ë¡¤í•´ë„ ìƒë‹¨ ê³ ì • ì›í•˜ë©´ ì£¼ì„ í•´ì œ
    left:
      - text: "ê¸°ì´ˆìˆ˜í•™"
        menu:
          - href: notes/math/function.qmd
            text: "í•¨ìˆ˜"
          - href: notes/math/derivate_integral.qmd   # ì‹¤ì œ íŒŒì¼ëª… í™•ì¸!
            text: "ë¯¸ë¶„ì ë¶„"
          - href: notes/math/vector.qmd
            text: "ë²¡í„°"
          - href: notes/math/matrix.qmd
            text: "í–‰ë ¬"

      - text: "ìˆ˜ë¦¬í†µê³„"
        menu:
          - href: notes/math_stat/probability.qmd
            text: "í™•ë¥ "
          - href: notes/math_stat/random_variable.qmd
            text: "í™•ë¥ ë³€ìˆ˜"
          - href: notes/math_stat/famous_distribution.qmd
            text: "ìœ ëª…í•œë¶„í¬"
          - href: notes/math_stat/multi_variate.qmd
            text: "ë‹¤ë³€ëŸ‰í™•ë¥ ë³€ìˆ˜"
          - href: notes/math_stat/random_sample.qmd
            text: "í™•ë¥ í‘œë³¸_ë‚œìˆ˜ìƒì„±"
          - href: notes/math_stat/estimation.qmd
            text: "ì¶”ì •"
          - href: notes/math_stat/hypothesis_testing.qmd
            text: "ê°€ì„¤ê²€ì •_ì‹ ë¢°êµ¬ê°„"

      - text: "ì¼ë³€ëŸ‰ë¶„ì„"
        menu:
          - href: notes/intro_stat/concept_of_stat.qmd
            text: "ì¼ë³€ëŸ‰ë¶„ì„ ê°œë…"
          - href: notes/intro_stat/data.qmd
            text: "ë°ì´í„°ì™€ í†µê³„"
          - href: notes/intro_stat/univariate.qmd
            text: "ì¼ë³€ëŸ‰ë¶„ì„"
          - href: notes/intro_stat/crosstab.qmd
            text: "êµì°¨í‘œë¶„ì„"
          - href: notes/intro_stat/goodness_of_fits.qmd
            text: "ì í•©ì„±ê²€ì •"
          - href: notes/intro_stat/normality.qmd
            text: "ì •ê·œë³€í™˜"
          - href: notes/intro_stat/correlation.qmd
            text: "ìƒê´€ë¶„ì„"
          - href: notes/intro_stat/anova.qmd
            text: "ì‹¤í—˜ì„¤ê³„ ë¶„ì‚°ë¶„ì„"
          - href: notes/intro_stat/time_series.qmd
            text: "ì‹œê³„ì—´ë¶„ì„"

      - text: "ì¡°ì‚¬ë°©ë²•ë¡ "
        menu:
          - href: notes/survey/survey_intro.qmd
            text: "ì¡°ì‚¬ë°©ë²• ê¸°ì´ˆ"
          - href: notes/survey/sample_design.qmd
            text: "í‘œë³¸ì„¤ê³„"
          - href: notes/survey/questionnaire.qmd
            text: "ì„¤ë¬¸ì§€"
          - href: notes/survey/nonresponse.qmd
            text: "ë¬´ì‘ë‹µ ëŒ€ì²´"
          - href: notes/survey/data_process.qmd
            text: "ë°ì´í„° ì²˜ë¦¬"
          - href: notes/survey/survey_scale.qmd
            text: "ì¡°ì‚¬ì§€ ì²™ë„"
          - href: notes/survey/delphi_ahp_conjoint.qmd
            text: "ë¸íŒŒì´_AHP_ì»¨ì¡°ì¸íŠ¸"
          - href: notes/survey/psm.qmd
            text: "PSM ì„±í–¥ì ìˆ˜ë§¤ì¹­"

      - text: "íšŒê·€ë¶„ì„"
        menu:
          - href: notes/linear_model/lm_concept.qmd
            text: "íšŒê·€ë¶„ì„ ê°œë…&ì¶”ì •"
          - href: notes/linear_model/lm_selection.qmd
            text: "ë³€ìˆ˜ì„ íƒ"
          - href: notes/linear_model/lm_multicolin.qmd
            text: "ë‹¤ì¤‘ê³µì„ ì„±"
          - href: notes/linear_model/lm_diagnosis.qmd
            text: "íšŒê·€ì§„ë‹¨"
          - href: notes/linear_model/lm_logistic.qmd
            text: "ë¡œì§€ìŠ¤í‹±íšŒê·€"

      - text: "ë‹¤ë³€ëŸ‰ë¶„ì„"
        menu:
          - href: notes/mda/mda_concepts.qmd
            text: "ë‹¤ë³€ëŸ‰ë¶„ì„ ê°œë…"
          - href: https://by-sekwon.github.io/notes/intro_stat/correlation.html#chapter-3.-%EB%8B%A4%EB%B3%80%EB%9F%89-%EC%83%81%EA%B4%80%EA%B3%84%EC%88%98
            text: "ë‹¤ë³€ëŸ‰ ìƒê´€ê³„ìˆ˜"
          - href: notes/mda/mda_pca.qmd
            text: "ì£¼ì„±ë¶„ë¶„ì„ svd"
          - href: notes/mda/mda_factor.qmd
            text: "ìš”ì¸ë¶„ì„ êµ¬ì¡°ë°©ì •ì‹" 
          - href: notes/mda/mda_discriminant.qmd
            text: "íŒë³„ë¶„ì„ Fisher|Logistic" 
          - href: notes/mda/mda_cluster.qmd
            text: "êµ°ì§‘ë¶„ì„ ê³„ì¸µì |ë¹„ê³„ì¸µì ë°©ë²•" 
          - href: notes/mda/mda_mds_ca.qmd
            text: "ë‹¤ì°¨ì›ì²™ë„ë²•|ëŒ€ì‘ë¶„ì„" 
          - href: notes/mda/mda_cancorr_manova.qmd
            text: "ì •ì¤€ìƒê´€ë¶„ì„|ë‹¤ë³€ëŸ‰ë¶„ì‚°ë¶„ì„" 
      - text: "MLDL w/GPT"
        menu:
          - href: notes/mldl/mldl_concepts.qmd
            text: "ë¨¸ì‹ ëŸ¬ë‹ í†µê³„ì ì‚¬ê³ "

      - href: cardnews/index.qmd
        text: "ì¹´ë“œë‰´ìŠ¤"

      - href: consult.qmd
        text: "í†µê³„ìƒë‹´"

      - text: "ğŸ“¡ìŠ¤íŠ¸ë¦¬ë°"
        menu:
          - href: https://by-sekwonappio-esqshnv7wueapp4da6jrizn.streamlit.app
            text: "ì‹¤ì‹œê°„ì£¼ê°€[5ëŒ€ì¢…ëª©]"
            target: _blank
          - href: https://by-sekwonappio-k5e5n7wasvj3kveyqbwmgc.streamlit.app/
            text: "ëŒ€ì „ìœ ì„±êµ¬ ì¼ê¸°ì˜ˆë³´"
            target: _blank

  # (ì„ íƒ) ê¹ƒí—ˆë¸Œ ë¦¬í¬ì§€í† ë¦¬ ë²„íŠ¼
  repo-url: https://github.com/by-sekwon/by-sekwon.github.io
  repo-actions: []

  # (ì„ íƒ) í‘¸í„°
  page-footer:
    left: "Â© 2025 Kwon"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    highlight-style: tango
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "ëª©ì°¨"
    toc-location: left
    # number-sections: true   # â† ìˆ«ì ì œê±°: ì´ ì¤„ì„ ì§€ì›ë‹ˆë‹¤
    code-copy: true
    anchor-sections: true
    link-external-newwindow: true
    fig-cap-location: top
    tbl-cap-location: top

lang: ko
freeze: auto