project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

website:
  title: "세상의 모든 통계 이야기"

  navbar:
    left:
      - text: "기초수학"
        href: notes/math/index.qmd
      - text: "수리통계"
        href: notes/math_stat/index.qmd
      - text: "기초통계"
        href: notes/intro_stat/index.qmd
      - text: "조사방법론"
        href: notes/survey/index.qmd
      - text: "회귀분석"
        href: notes/linear_model/index.qmd
      - text: "다변량분석"
        href: notes/mda/index.qmd
      - text: "머신·딥러닝 개념 w/GPT"
        href: notes/mldl/index.qmd
      - text: "머신·딥러닝 방법론 w/GPT"
        href: notes/mldl_method/index.qmd
      - text: "카드뉴스"
        href: cardnews/index.qmd
      - text: "통계상담"
        href: consult.qmd

  sidebar:
    - id: math
      title: "기초수학"
      style: docked
      search: false
      contents:
        - href: notes/math/index.qmd
          text: "【HOME】"
        - href: notes/math/function.qmd
          text: "▶︎ 함수"
        - href: notes/math/derivate_integral.qmd
          text: "▶︎ 미분적분"
        - href: notes/math/vector.qmd
          text: "▶︎ 벡터"
        - href: notes/math/matrix.qmd
          text: "▶︎ 행렬"

    - id: math_stat
      title: "수리통계"
      style: docked
      search: false
      contents:
        - href: notes/math_stat/index.qmd
          text: "【HOME】"
        - href: notes/math_stat/probability.qmd
          text: "▶︎ 확률"
        - href: notes/math_stat/random_variable.qmd
          text: "▶︎ 확률변수"
        - href: notes/math_stat/famous_distribution.qmd
          text: "▶︎ 유명한 분포"
        - href: notes/math_stat/multi_variate.qmd
          text: "▶︎ 다변량확률변수"
        - href: notes/math_stat/random_sample.qmd
          text: "▶︎ 확률표본·난수"
        - href: notes/math_stat/estimation.qmd
          text: "▶︎ 추정"
        - href: notes/math_stat/hypothesis_testing.qmd
          text: "▶︎ 가설검정·신뢰구간"

    - id: intro_stat
      title: "기초통계"
      style: docked
      search: false
      contents:
        - href: notes/intro_stat/index.qmd
          text: "【HOME】"
        - href: notes/intro_stat/concept_of_stat.qmd
          text: "▶︎ 통계학의 개념"
        - href: notes/intro_stat/data.qmd
          text: "▶︎ 데이터와 통계"
        - href: notes/intro_stat/univariate.qmd
          text: "▶︎ 일변량 분석"
        - href: notes/intro_stat/crosstab.qmd
          text: "▶︎ 교차표 분석"
        - href: notes/intro_stat/goodness_of_fits.qmd
          text: "▶︎ 적합성 검정"
        - href: notes/intro_stat/normality.qmd
          text: "▶︎ 정규성 검정"
        - href: notes/intro_stat/correlation.qmd
          text: "▶︎ 상관분석"
        - href: notes/intro_stat/anova.qmd
          text: "▶︎ 분산분석(ANOVA)"
        - href: notes/intro_stat/time_series.qmd
          text: "▶︎ 시계열 분석"

    - id: survey
      title: "조사방법론"
      style: docked
      search: false
      contents:
        - href: notes/survey/index.qmd
          text: "【HOME】"
        - href: notes/survey/survey_intro.qmd
          text: "▶︎ 조사방법 기초"
        - href: notes/survey/sample_design.qmd
          text: "▶︎ 표본설계"
        - href: notes/survey/questionnaire.qmd
          text: "▶︎ 설문지"
        - href: notes/survey/nonresponse.qmd
          text: "▶︎ 무응답 대체"
        - href: notes/survey/data_process.qmd
          text: "▶︎ 데이터 처리"
        - href: notes/survey/survey_scale.qmd
          text: "▶︎ 조사지 척도"
        - href: notes/survey/delphi_ahp_conjoint.qmd
          text: "▶︎ 델파이·AHP·컨조인트"
        - href: notes/survey/psm.qmd
          text: "▶︎ PSM 성향점수매칭"

    - id: linear_model
      title: "회귀분석"
      style: docked
      search: false
      contents:
        - href: notes/linear_model/index.qmd
          text: "【HOME】"
        - href: notes/linear_model/lm_concept.qmd
          text: "▶︎ 개념·추정"
        - href: notes/linear_model/lm_selection.qmd
          text: "▶︎ 변수선택"
        - href: notes/linear_model/lm_multicolin.qmd
          text: "▶︎ 다중공선성"
        - href: notes/linear_model/lm_diagnosis.qmd
          text: "▶︎ 회귀진단"
        - href: notes/linear_model/lm_logistic.qmd
          text: "▶︎ 로지스틱회귀"

    - id: mda
      title: "다변량분석"
      style: docked
      search: false
      contents:
        - href: notes/mda/index.qmd
          text: "【HOME】"
        - href: notes/mda/mda_concepts.qmd
          text: "▶︎ 개요"
        - href: notes/mda/mda_pca.qmd
          text: "▶︎ PCA"
        - href: notes/mda/mda_factor.qmd
          text: "▶︎ 요인분석"
        - href: notes/mda/mda_cluster.qmd
          text: "▶︎ 군집분석"
        - href: notes/mda/mda_discriminant.qmd
          text: "▶︎ 판별분석"
        - href: notes/mda/mda_mds_ca.qmd
          text: "▶︎ MDS·CA"
        - href: notes/mda/mda_cancorr_manova.qmd
          text: "▶︎ 정준상관·MANOVA"

    - id: mldl
      title: "머신·딥러닝 개념"
      style: docked
      search: false
      contents:
        - href: notes/mldl/index.qmd
          text: "【HOME】"
        - href: notes/mldl/mldl_concepts.qmd
          text: "▶︎ 개요"
        - href: notes/mldl/mldl_concepts01.qmd
          text: "▶︎ 개념 1"
        - href: notes/mldl/mldl_concepts02.qmd
          text: "▶︎ 개념 2"
        - href: notes/mldl/mldl_supervised.qmd
          text: "▶︎ 지도학습"
        - href: notes/mldl/mldl_unsupervised.qmd
          text: "▶︎ 비지도학습"
        - href: notes/mldl/mldl_evaluation.qmd
          text: "▶︎ 평가"
        - href: notes/mldl/mldl_uncertainty.qmd
          text: "▶︎ 불확실성"
        - href: notes/mldl/mldl_deeplearning.qmd
          text: "▶︎ 딥러닝"

    - id: mldl_method
      title: "머신·딥러닝 방법론"
      style: docked
      search: false
      contents:
        - href: notes/mldl_method/index.qmd
          text: "【HOME】"
        - href: notes/mldl_method/mldlmethod_introduction.qmd
          text: "▶︎ 방법론 소개"