project:
  type: website
  output-dir: docs
format:
  html:
    theme: cosmo
    css: styles.css   # â† ì—¬ê¸°ì— ë°©ê¸ˆ ë§Œë“  CSS íŒŒì¼ëª… ì…ë ¥
    
website:
  title: "ì„¸ìƒì˜ ëª¨ë“  í†µê³„ ì´ì•¼ê¸°"
  navbar:
    left:
      - text: "|ê¸°ì´ˆìˆ˜í•™|"
        menu:
          - href: notes/math/function.qmd
            text: "í•¨ìˆ˜"
          - href: notes/math/derivate_integral.qmd
            text: "ë¯¸ë¶„ì ë¶„"
          - href: notes/math/vector.qmd
            text: "ë²¡í„°"
          - href: notes/math/matrix.qmd
            text: "í–‰ë ¬"
      - text: "|ìˆ˜ë¦¬í†µê³„|"
        menu:
          - href: notes/math_stat/probability.qmd
            text: "í™•ë¥ "
          - href: notes/math_stat/random_variable.qmd
            text: "í™•ë¥ ë³€ìˆ˜"
          - href: notes/math_stat/famous_distribution.qmd
            text: "ìœ ëª…í•œë¶„í¬"
          - href: notes/math_stat/multi_variate.qmd
            text: "ë‹¤ë³€ëŸ‰í™•ë¥ ë³€ìˆ˜"
          - href: notes/math_stat/random_sample.qmd
            text: "í™•ë¥ í‘œë³¸"
          - href: notes/math_stat/inference.qmd
            text: "ì¶”ì •ê³¼ê²€ì •"
      - text: "|ì¡°ì‚¬ë°©ë²•|"
        menu:
          - href: notes/survey/survey_intro.qmd
            text: "ì¡°ì‚¬ë°©ë²• ê¸°ì´ˆ"
          - href: notes/survey/sample_design.qmd
            text: "í‘œë³¸ì„¤ê³„"
          - href: notes/survey/questionnaire.qmd
            text: "ì„¤ë¬¸ì§€"
          - href: notes/survey/nonresponse.qmd
            text: "ë¬´ì‘ë‹µ ëŒ€ì²´"
          - href: notes/survey/data_process.qmd
            text: "ë°ì´í„° ì²˜ë¦¬"
          - href: notes/survey/survey_scale.qmd
            text: "ì¡°ì‚¬ì§€ ì²™ë„"
          - href: notes/survey/delphi_ahp_conjoint.qmd
            text: "ë¸íŒŒì´ AHP ì»¨ì¡°ì¸íŠ¸"
      - href: cardnews\index.qmd
        text: \| ì¹´ë“œë‰´ìŠ¤ |
      - href: consult.qmd
        text: \| í†µê³„ìƒë‹´ |
      - text: "ğŸ“¡ ìŠ¤íŠ¸ë¦¬ë°"
        menu:
          - href: https://by-sekwonappio-esqshnv7wueapp4da6jrizn.streamlit.app
            text: "ì‹¤ì‹œê°„ì£¼ê°€[5ëŒ€ì¢…ëª©]"
          - href: https://by-sekwonappio-k5e5n7wasvj3kveyqbwmgc.streamlit.app/
            text: "ëŒ€ì „ìœ ì„±êµ¬ ì¼ê¸°ì˜ˆë³´"