project:
  type: website
  output-dir: docs

website:
  title: "ì„¸ìƒì˜ ëª¨ë“  í†µê³„ ì´ì•¼ê¸°"
  navbar:
    left:
      - href: index.qmd
        text: í™ˆ
      - href: notes/math/index.qmd
        text: \| ìˆ˜í•™ê¸°ì´ˆ |
      - href: notes/intro_stat/index.qmd
        text: \| ê¸°ì´ˆí†µê³„ |
      - href: notes/advance_stat/index.qmd
        text: \| ê³ ê¸‰í†µê³„ |
      - href: notes/mldl/index.qmd
        text: \| MLDL |
      - href: cards/news01.qmd
        text: \| ì¹´ë“œë‰´ìŠ¤ |
      - href: consult.qmd
        text: \| í†µê³„ìƒë‹´ |
      - text: "ğŸ“¡ ìŠ¤íŠ¸ë¦¬ë°"
        menu:
          - href: https://by-sekwonappio-esqshnv7wueapp4da6jrizn.streamlit.app
            text: "ì‹¤ì‹œê°„ì£¼ê°€[5ëŒ€ì¢…ëª©]"
          - href: https://by-sekwonappio-k5e5n7wasvj3kveyqbwmgc.streamlit.app
            text: "ëŒ€ì „ìœ ì„±êµ¬ ì¼ê¸°ì˜ˆë³´"