project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "ëª©ì°¨"
    toc-depth: 4

website:
  title: "ì„¸ìƒì˜ ëª¨ë“  í†µê³„ ì´ì•¼ê¸°"

  navbar:
    left:
      - text: "ê¸°ì´ˆ|ìˆ˜ë¦¬í†µê³„"
        href: notes/math_stat/index.qmd
      - text: "ê¸°ì´ˆí†µê³„|ì¡°ì‚¬ë°©ë²•"
        href: notes/intro_stat/index.qmd
      - text: "íšŒê·€ë¶„ì„|ë‹¤ë³€ëŸ‰ë¶„ì„"
        href: notes/linear_model/index.qmd
      - text: "ë¨¸ì‹ Â·ë”¥ëŸ¬ë‹ ê°œë… w/GPT"
        href: notes/mldl/index.qmd
      - text: "ë¨¸ì‹ Â·ë”¥ëŸ¬ë‹ ì˜ˆì¸¡ë°©ë²• w/GPT"
        href: notes/mldl_method/index.qmd
      - text: "ì¹´ë“œë‰´ìŠ¤"
        href: cardnews/index.qmd
      - text: "í†µê³„ìƒë‹´"
        href: consult.qmd

  sidebar:
    - id: math_stat
      title: "ê¸°ì´ˆ|ìˆ˜ë¦¬í†µê³„"
      style: docked
      search: false
      contents: 
        - href: notes/math/index.qmd
          text: "ã€ê¸°ì´ˆìˆ˜í•™ã€‘"
        - href: notes/math/function.qmd
          text: "ğŸ“„ í•¨ìˆ˜"
        - href: notes/math/derivate_integral.qmd
          text: "ğŸ“„ ë¯¸ë¶„ì ë¶„"
        - href: notes/math/vector.qmd
          text: "ğŸ“„ ë²¡í„°"
        - href: notes/math/matrix.qmd
          text: "ğŸ“„ í–‰ë ¬" 
        - href: notes/math_stat/index.qmd
          text: "ã€ìˆ˜ë¦¬í†µê³„ã€‘"
        - href: notes/math_stat/probability.qmd
          text: "ğŸ“„ í™•ë¥ "
        - href: notes/math_stat/random_variable.qmd
          text: "ğŸ“„ í™•ë¥ ë³€ìˆ˜"
        - href: notes/math_stat/famous_distribution.qmd
          text: "ğŸ“„ ìœ ëª…í•œ ë¶„í¬"
        - href: notes/math_stat/multi_variate.qmd
          text: "ğŸ“„ ë‹¤ë³€ëŸ‰í™•ë¥ ë³€ìˆ˜"
        - href: notes/math_stat/random_sample.qmd
          text: "ğŸ“„ í™•ë¥ í‘œë³¸Â·ë‚œìˆ˜"
        - href: notes/math_stat/estimation.qmd
          text: "ğŸ“„ ì¶”ì •"
        - href: notes/math_stat/hypothesis_testing.qmd
          text: "ğŸ“„ ê°€ì„¤ê²€ì •Â·ì‹ ë¢°êµ¬ê°„"
              
    - id: intro_stat
      title: "ê¸°ì´ˆí†µê³„"
      style: docked
      search: false
      contents:
        - href: notes/intro_stat/index.qmd
          text: "ã€ê¸°ì´ˆí†µê³„ã€‘"
        - href: notes/intro_stat/concept_of_stat.qmd
          text: "ğŸ“„ í†µê³„í•™ì˜ ê°œë…"
        - href: notes/intro_stat/data.qmd
          text: "ğŸ“„ ë°ì´í„°ì™€ í†µê³„"
        - href: notes/intro_stat/univariate.qmd
          text: "ğŸ“„ ì¼ë³€ëŸ‰ ë¶„ì„"
        - href: notes/intro_stat/crosstab.qmd
          text: "ğŸ“„ êµì°¨í‘œ ë¶„ì„"
        - href: notes/intro_stat/goodness_of_fits.qmd
          text: "ğŸ“„ ì í•©ì„± ê²€ì •"
        - href: notes/intro_stat/normality.qmd
          text: "ğŸ“„ ì •ê·œì„± ê²€ì •"
        - href: notes/intro_stat/correlation.qmd
          text: "ğŸ“„ ìƒê´€ë¶„ì„"
        - href: notes/intro_stat/anova.qmd
          text: "ğŸ“„ ë¶„ì‚°ë¶„ì„(ANOVA)"
        - href: notes/intro_stat/time_series.qmd
          text: "ğŸ“„ ì‹œê³„ì—´ ë¶„ì„"
        - href: notes/survey/index.qmd
          text: "ã€ì¡°ì‚¬ë°©ë²•ë¡ ã€‘"
        - href: notes/survey/survey_intro.qmd
          text: "ğŸ“„ ì¡°ì‚¬ë°©ë²• ê¸°ì´ˆ"
        - href: notes/survey/sample_design.qmd
          text: "ğŸ“„ í‘œë³¸ì„¤ê³„"
        - href: notes/survey/questionnaire.qmd
          text: "ğŸ“„ ì„¤ë¬¸ì§€"
        - href: notes/survey/nonresponse.qmd
          text: "ğŸ“„ ë¬´ì‘ë‹µ ëŒ€ì²´"
        - href: notes/survey/data_process.qmd
          text: "ğŸ“„ ë°ì´í„° ì²˜ë¦¬"
        - href: notes/survey/survey_scale.qmd
          text: "ğŸ“„ ì¡°ì‚¬ì§€ ì²™ë„"
        - href: notes/survey/delphi_ahp_conjoint.qmd
          text: "ğŸ“„ ë¸íŒŒì´Â·AHPÂ·ì»¨ì¡°ì¸íŠ¸"
        - href: notes/survey/psm.qmd
          text: "ğŸ“„ PSM ì„±í–¥ì ìˆ˜ë§¤ì¹­"

    - id: linear_model
      title: "íšŒê·€ë¶„ì„"
      style: docked
      search: false
      contents:
        - href: notes/linear_model/index.qmd
          text: "ã€íšŒê·€ë¶„ì„ã€‘"
        - href: notes/linear_model/lm_concept.qmd
          text: "ğŸ“„ ê°œë…Â·ì¶”ì •"
        - href: notes/linear_model/lm_selection.qmd
          text: "ğŸ“„ ë³€ìˆ˜ì„ íƒ"
        - href: notes/linear_model/lm_multicolin.qmd
          text: "ğŸ“„ ë‹¤ì¤‘ê³µì„ ì„±"
        - href: notes/linear_model/lm_diagnosis.qmd
          text: "ğŸ“„ íšŒê·€ì§„ë‹¨"
        - href: notes/linear_model/lm_logistic.qmd
          text: "ğŸ“„ ë¡œì§€ìŠ¤í‹±íšŒê·€"
        - href: notes/mda/index.qmd
          text: "ã€ë‹¤ë³€ëŸ‰ë¶„ì„ã€‘"
        - href: notes/mda/mda_concepts.qmd
          text: "ğŸ“„ ê°œìš”"
        - href: notes/mda/mda_pca.qmd
          text: "ğŸ“„ PCA"
        - href: notes/mda/mda_factor.qmd
          text: "ğŸ“„ ìš”ì¸ë¶„ì„"
        - href: notes/mda/mda_cluster.qmd
          text: "ğŸ“„ êµ°ì§‘ë¶„ì„"
        - href: notes/mda/mda_discriminant.qmd
          text: "ğŸ“„ íŒë³„ë¶„ì„"
        - href: notes/mda/mda_mds_ca.qmd
          text: "ğŸ“„ ë‹¤ì°¨ì›ì²™ë„Â·ëŒ€ì‘ë¶„ì„"
        - href: notes/mda/mda_cancorr_manova.qmd
          text: "ğŸ“„ ì •ì¤€ìƒê´€Â·MANOVA"

    - id: mldl
      title: "ë¨¸ì‹ Â·ë”¥ëŸ¬ë‹ ê°œë…"
      style: docked
      search: false
      contents:
        - href: notes/mldl/index.qmd
          text: "ã€ë¨¸ì‹ Â·ë”¥ëŸ¬ë‹ ê°œë…ã€‘"
        - href: notes/mldl/mldl_concepts.qmd
          text: "ğŸ“„ ê°œìš”"
        - href: notes/mldl/mldl_concepts01.qmd
          text: "ğŸ“„ MLDL ê°œë… 1"
        - href: notes/mldl/mldl_concepts02.qmd
          text: "ğŸ“„ MLDL ê°œë… 2"
        - href: notes/mldl/mldl_supervised.qmd
          text: "ğŸ“„ ì§€ë„í•™ìŠµ"
        - href: notes/mldl/mldl_unsupervised.qmd
          text: "ğŸ“„ ë¹„ì§€ë„í•™ìŠµ"
        - href: notes/mldl/mldl_evaluation.qmd
          text: "ğŸ“„ í‰ê°€"
        - href: notes/mldl/mldl_uncertainty.qmd
          text: "ğŸ“„ ë¶ˆí™•ì‹¤ì„±"
        - href: notes/mldl/mldl_deeplearning.qmd
          text: "ğŸ“„ ë”¥ëŸ¬ë‹"

    - id: mldl_method
      title: "ë¨¸ì‹ Â·ë”¥ëŸ¬ë‹ ë°©ë²•ë¡ "
      style: docked
      search: false
      contents:
        - href: notes/mldl_method/index.qmd
          text: "ã€ë¨¸ì‹ Â·ë”¥ëŸ¬ë‹ ì˜ˆì¸¡ë°©ë²•ã€‘"
        - href: notes/mldl_method/mldlmethod_introduction.qmd
          text: "ğŸ“„ MLDL ë°©ë²•ë¡  ì†Œê°œ"
        - href: notes/mldl_method/mldlmethod_prediction_intro.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: ì„œë¡ "
        - href: notes/mldl_method/mldlmethod_prediction_reg.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: íšŒê·€ë¶„ì„"
        - href: notes/mldl_method/mldlmethod_prediction_regulation.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: ê·œì œíšŒê·€"
        - href: notes/mldl_method/mldlmethod_prediction_dimension.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: ì°¨ì›ì¶•ì†Œ"
        - href: notes/mldl_method/mldlmethod_prediction_nonreg.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: ë¹„ì„ í˜•íšŒê·€"
        - href: notes/mldl_method/mldlmethod_prediction_treebase.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: íŠ¸ë¦¬ê¸°ë°˜"
        - href: notes/mldl_method/mldlmethod_prediction_deeplearning.qmd
          text: "ğŸ“„ ì˜ˆì¸¡ë°©ë²•: ë”¥ëŸ¬ë‹íšŒê·€"
