project:
  type: website
  output-dir: docs

website:
  title: "ì„¸ìƒì˜ ëª¨ë“  í†µê³„ ì´ì•¼ê¸°"
  navbar:
    left:
      - text: "ğŸ”¢ ê¸°ì´ˆìˆ˜í•™"
        menu:
          - href: notes/math/function.qmd
            text: "í•¨ìˆ˜"
          - href: notes/math/derivate_integral.qmd
            text: "ë¯¸ë¶„ì ë¶„"
          - href: notes/math/vector.qmd
            text: "ë²¡í„°"
          - href: notes/math/matrix.qmd
            text: "í–‰ë ¬"
      - href: cards/news01.qmd
        text: \| ì¹´ë“œë‰´ìŠ¤ |
      - href: consult.qmd
        text: \| í†µê³„ìƒë‹´ |
      - text: "ğŸ“¡ ìŠ¤íŠ¸ë¦¬ë°"
        menu:
          - href: https://by-sekwonappio-esqshnv7wueapp4da6jrizn.streamlit.app
            text: "ì‹¤ì‹œê°„ì£¼ê°€[5ëŒ€ì¢…ëª©]"
          - href: https://by-sekwonappio-k5e5n7wasvj3kveyqbwmgc.streamlit.app/
            text: "ëŒ€ì „ìœ ì„±êµ¬ ì¼ê¸°ì˜ˆë³´"